version: "2"
services:

# node:
#   build: .
#   ports:
#    - 3123:3123
#   depends_on:
#    - database
#   links:
#    - database
#   working_dir: /usr/local/src/app
#   volumes:
#    - .:/usr/local/src/app
#   command: bash -c "npm install && npm run dev"

 database:
    image: postgres:9.6
    ports:
     - 5411:5432
    volumes:
     - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: base

volumes:
 data: {}
